### ISSUE TITLE
why is the number of prompt  zero  in cfg file

### ISSUE THREAD

**Issue by TangYuan96** [RunpeiDong/ACT#1]
Firstly, thanks for sharing  you outstanding work!

why is the number of prompt  zero  in  ./cfgs/autoencoder/act_dvae_with_pretrained_transformer.yaml?

following as :
  num_prompt_token: 0
  use_deep_prompt: false

Could you provide the cfg file when you train   the dvae  ?

Thank you!

**Comment by RunpeiDong** [comment]
Hi @TangYuan96,
Thanks for your interest in our work and for pointing out this question. The current config is the basic case and can be modified. By default, the `num_prompt_token` should be `64`, and `use_deep_prompt` should be `True`. I will change this into the default config to avoid misunderstandings.

**Comment by TangYuan96** [comment]
I get it . Thanks for your response！！
