### ISSUE TITLE
how many  the number  of point  from one room is used  in  S3DIS test?

### ISSUE THREAD

**Issue by TangYuan96** [RunpeiDong/ACT#4]
Hi，Thanks for your reply before!!

I have some questions.

1. Is the results about S3DIS reported in Table 4 is from main.py ( running semantic_segmentation/main.py)  or  main_test.py(semantic_segmentation/main_test.py)?

2. Is the number of points we used in S3DIS  test 2048?

3. Why not use the all points of one room?

Look forward your reply~

**Comment by RunpeiDong** [comment]
Hi @TangYuan96,

- The results are obtained by running `semantic_segmentation/main.py`, the test split is the same, i.e., the test split on Area 5.
- The number of points is 2048 for S3DIS following PointNet++, Pix4Point, PointNeXt, etc.
- The reason for not using all points is maybe that the number of all points in a scene is too large. You can try using 4096 points as inputs like DeepGCN, but the compared methods should be updated.

**Comment by TangYuan96** [comment]
thanks for your so careful reply!!
