### ISSUE TITLE
How to get the visualization results?

### ISSUE THREAD

**Issue by Daybreak-Zheng** [RunpeiDong/ACT#5]
How to visualise the reconstructed results?
Looking forward to your reply!

**Comment by RunpeiDong** [comment]
Hi @Daybreak-Zheng,

Thanks for asking. 

We use our own tool: https://github.com/qizekun/PointVisualizaiton for visualization. We highly recommend using this wonderful repo.

**Comment by Daybreak-Zheng** [comment]
Why is the plane nose-down left visible to me? 
![image](https://user-images.githubusercontent.com/44741080/233832587-2a055ae7-bab8-4d93-8993-035e4d4aad5d.png)

May I ask how can I modify the plane nose-up right, similar to the one in your paper

**Comment by RunpeiDong** [comment]
@Daybreak-Zheng,

Sure you can. You can set the pose of the 3D object by rotating the 3D point clouds with a rotation matrix (our practice), or you can modify the render pose (which may not be easy to get a satisfactory result).
