### ISSUE TITLE
Point cloud visualization

### ISSUE THREAD

**Issue by Daybreak-Zheng** [RunpeiDong/ACT#6]
When we were carrying out point cloud visualization, the point cloud Angle was wrong. Could you please provide the code of point cloud rotation?

Looking forward to your reply.

**Comment by RunpeiDong** [comment]
Hi @Daybreak-Zheng, we have updated the visualization [Repo](https://github.com/qizekun/PointVisualizaiton)  by supporting a rotation operation. Check it out, please.

**Comment by Daybreak-Zheng** [comment]
Very good work, thanks!

**Comment by RunpeiDong** [comment]
Leave a star if you think our repo is helpful.:)
