### ISSUE TITLE
t-SNE feature visualization

### ISSUE THREAD

**Issue by Daybreak-Zheng** [RunpeiDong/ACT#7]
Excellent work.
How do I get the results of t-SNE feature visualization?
Looking forward to your reply！

**Comment by RunpeiDong** [comment]
Hi @Daybreak-Zheng,

We use https://github.com/pavlin-policar/openTSNE which is a great tool. I have provided a script named main_tsne.py, please check it out. 

Hope this could help you.

Best,
Runpei

**Comment by Daybreak-Zheng** [comment]
How do I use it to get the visualisation I want?

**Comment by RunpeiDong** [comment]
Please read the code first.

Replace the file path [here](https://github.com/RunpeiDong/ACT/blob/f67e1f51ef91a43e28bc108a3ec2d5eefa5c46dc/tools/runner_tsne.py#L36) with your ckpt path. And use the corresponding config file to specify the model and dataset. Then run the code. 😸That's it.
